require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "bash",
        "c",
        "diff",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "hcl",
        "json",
        "lua",
        "make",
        "markdown",
        "mermaid",
        "python",
        "query",
        "regex",
        "rego",
        "terraform",
        "toml",
        "vim",
        "vimdoc",
        "yaml",
    },
    sync_install = false,
    ignore_install = {
        "phpdoc",
        -- "dockerfile"
    },
    highlight = {
      enable = false,
    },
})
