[tools]
cargo = "latest"
delta = "latest"
gem = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
neovim = "latest"
node = "latest"
npm = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
tfenv = "latest"
tmux = "latest"
uv = "latest"
yarn = "latest"
zoxide = "latest"
